### ISSUE TITLE
Feat(esm import dir): introduce

### ISSUE THREAD

**Issue by AugustinMauroy** [JakobJingleheimer/nodejs-loaders#8]
It would be useful to have a loader in this package that allows you to import directories into ESM.

For example, on a react+typescript project it's very common to use directory import even if it's not the ECMAScript spec. So the loader could facilitate migration from a tool like jest -> node test runner.

**Comment by JakobJingleheimer** [comment]
What would that look like?

```
./foo/
  a.js
  b.js
```

```js
import dir from './foo';
dir; // ['a.js', 'b.js']
```

I'm not necessarily opposed, but I don't see how it's useful.

Or do you mean commonjs-like imports like https://github.com/nodejs/loaders-test/tree/main/commonjs-extension-resolution-loader

I'm very hesitant to provide the latter for fear of merely facilitating bad practices (because then they'll never actually migrate).

**Comment by AugustinMauroy** [comment]
> Or do you mean commonjs-like imports like https://github.com/nodejs/loaders-test/tree/main/commonjs-extension-resolution-loader

I was talking about that, yes.

> I'm very hesitant to provide the latter for fear of merely facilitating bad practices (because then they'll never actually migrate).

I agree with you 100%. 

But in the case of a typescript project, typescript basically doesn't ask for extensions and outputs an error.
Also it may allow a better DX to migrate from one way of doing things to another.

That's why I was wondering if we couldn't implement this loader in the packager and issue a warn, at least that would force users not to use it x'D

If I had to be very hegosite it would be useful for me to migrate jest to node test runner without problem on nodejs.org 😁

**Comment by JakobJingleheimer** [comment]
> But in the case of a typescript project, typescript basically doesn't ask for extensions and outputs an error.

Ahhh. I see. It is possible (and ideal) to handle this a different way: type-checking should be a separate CI/CD step like linting and unit tests, and everything else should strip the types (otherwise, you're repeatedly paying the very very expensive cost of type-checking during unrelated tasks).

```json
{
  "scripts": {
    "build": "esbuild …",
    "test": "concurrently test:* …",
    "test:lint:css": "…",
    "test:lint:js": "…",
    "test:types": "tsc --noEmit --allowImportingTsExtensions",
    "test:units": "node --loader tsx --test './src/**/*.spec.mts'",
    "test:ui": "node --loader tsx --test './src/**/*.test.tsx'"
  }
}
```

Then source-code can (and absolutely _should_) use the correct file extensions within its import specifiers, and `tsc` will no-longer shit the bed.

VS Code also accepts this, so you still see type issues within the IDE and it doesn't complain about the file extensions (and can still follow them, correctly importing their types etc).

**Comment by AugustinMauroy** [comment]
Honestly, I think that such a loader will help in some cases, like migration, because you start by migrating `expect` => `assert` and then you change the imports.
But it can also break DX because I think no extension is not a good practice.

**Comment by JakobJingleheimer** [comment]
I'm still thinking no because it's not that difficult to fix the file extension problem. I did it for a rather large project. Took a couple hours to update the specifiers and adjust the CI/CD stuff.

It took me "longer" because there was a mix of files that could and could not be updated (some source-code was actually js, not ts). But for a fully ts project, that can be migrated wholesale and thus be much much faster (like a global find+replace: `.js';` → `.ts';`).

**Comment by AugustinMauroy** [comment]
> I think I would be more open to writing a codemod to try to automatically fix the import specifiers in source code.

Why not but that not the scope of this project.

I think we need to upgrade the docs a bit and explain why we don't provide a loader that resolves imports. 

This will close this issue.

**Comment by JakobJingleheimer** [comment]
> that not the scope of this project.

Oh for sure. I meant as a companion and then link to it in the docs like "this is not supported because it's wrong; use this to fix it"

**Comment by JakobJingleheimer** [comment]
https://github.com/JakobJingleheimer/correct-ts-specifiers

**Comment by JakobJingleheimer** [comment]
https://github.com/JakobJingleheimer/correct-ts-specifiers
